name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  provider: ^6.1.5+1
  shared_preferences: ^2.3.3
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  socket_io_client: ^3.1.2
  flutter_local_notifications: ^19.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
